type Post {
	id: Int!
	title: String!
	subTitle: String
	description: String
}

type Query {
	helloWorld: String!
}

type Mutation {
	addPost(newPostData: NewPostInput!): Post!
}

input NewPostInput {
	title: String!
  subTitle: String
	description: String
}

type Subscription {
	postAdded: Post!
}
